FROM openresty/openresty:bionic

RUN apt-get update && apt-get install -y \
    git \
    libsodium23 \
    libssl-dev

RUN opm install pintsized/lua-resty-http

ADD distilcrypto/libdistilcrypto.so /usr/lib
ADD distilcrypto/distilcrypto.lua /usr/local/openresty/site/lualib
ADD lua /usr/local/openresty/site/lualib/distil
ADD conf.d/default.conf /etc/nginx/conf.d/default.conf
