FROM openresty/openresty:bionic

# Install OPM Dependencies
RUN opm install ledgetech/lua-resty-http=0.14
RUN opm install jkeys089/lua-resty-hmac=0.03

# Install Luarocks Dependencies
RUN /usr/local/openresty/luajit/bin/luarocks install lua-zlib 1.2-0

ADD lua /usr/local/openresty/site/lualib/distil
ADD conf.d/default.conf /etc/nginx/conf.d/default.conf
